### PR TITLE
Added new playground game Merge Away

### PR DESCRIPTION
**Pull request by Fy0urM**

### CODE REVIEW

**Comment by Sovenok-Hacker** [comment]
Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx, found the code but not the tokens.

**Comment by Fy0urM** [comment]
I found it on github by searching "hamster kombat", sorting by "recently updated" and checking a few repos.

**Comment by Sovenok-Hacker** [comment]
> I found it on github by searching "hamster kombat", sorting by "recently updated" and checking a few repos.

So you don't know how to extract them? Ok, very sad

**Review by hashidosperb — APPROVED** [review]

**Comment by Metercedes** [comment]
> Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx and found the code but not the tokens.

Those key codes are completely server-sided. That is why you failed to find them. In my opinion, there is a timer in these 5 games. So when the timer expires, it requests from a server to generate and provide a code. Because based on my experience and after some research by using iGameGod, I figured out this. But it may be false information tho, I didn't check that deeply. Just the behaviour of the games is in this way.

**Review by masterking32 — APPROVED** [review]
Thanks

**Comment by Sovenok-Hacker** [comment]
> > Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx and found the code but not the tokens.
> 
> Those key codes are completely server-sided. That is why you failed to find them. In my opinion, there is a timer in these 5 games. So when the timer expires, it requests from a server to generate and provide a code. Because based on my experience and after some research by using iGameGod, I figured out this. But it may be false information tho, I didn't check that deeply. Just the behaviour of the games is in this way.

But how do @masterking32 get them?

**Comment by masterking32** [comment]
> > > Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx and found the code but not the tokens.
> > 
> > 
> > Those key codes are completely server-sided. That is why you failed to find them. In my opinion, there is a timer in these 5 games. So when the timer expires, it requests from a server to generate and provide a code. Because based on my experience and after some research by using iGameGod, I figured out this. But it may be false information tho, I didn't check that deeply. Just the behaviour of the games is in this way.
> 
> But how do @masterking32 get them?

There is an API to create keys for other games. You can check the game's requests to find the API requests for generating new keys. The keys are generated by server-side requests when you finish a task in those games. They will send a request to the API to generate a key for you.

**Comment by Metercedes** [comment]
> > > > Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx and found the code but not the tokens.
> 
> > > 
> 
> > > 
> 
> > > Those key codes are completely server-sided. That is why you failed to find them. In my opinion, there is a timer in these 5 games. So when the timer expires, it requests from a server to generate and provide a code. Because based on my experience and after some research by using iGameGod, I figured out this. But it may be false information tho, I didn't check that deeply. Just the behaviour of the games is in this way.
> 
> > 
> 
> > But how do @masterking32 get them?
> 
> 
> 
> There is an API to create keys for other games. You can check the game's requests to find the API requests for generating new keys. The keys are generated by server-side requests when you finish a task in those games. They will send a request to the API to generate a key for you.
> 
> 

You right, however the code that you've provided doesn't seem to be registering them properly. It always stuck on 'registering' I created a pull-request about that.

**Comment by Metercedes** [comment]
> > > Can you please tell me how to get the tokens? I am not a professional reverse engineer, but I have tried reversing all the games and failed. I have no idea where these keys are in the game. I have decompiled the games with IL2Cpp and dnSpyEx and found the code but not the tokens.
> 
> > 
> 
> > Those key codes are completely server-sided. That is why you failed to find them. In my opinion, there is a timer in these 5 games. So when the timer expires, it requests from a server to generate and provide a code. Because based on my experience and after some research by using iGameGod, I figured out this. But it may be false information tho, I didn't check that deeply. Just the behaviour of the games is in this way.
> 
> 
> 
> But how do @masterking32 get them?

He is a specialist. He probably figured out what happens in each game after completing neccesary tasks. So in these matters he let that scropt obtaining codes immediatley. I have no such experience so whatever I say will be a lie/theory. However, @masterking32 's script failing to assign those codes into the game. So I suggest him to update script to add a manual function which lets you see the codes. I may try to work on that but it will take time, again I have no such experience. @masterking32 I have a special request from you, if possible could you also make a script which obtain keys but doesn't apply, instead stores it in a text file or just keeps on logs. My friend also need those codes but he doesn't wanna use script. So I wonder ehat should I do?

**Comment by masterking32** [comment]
We don't know the exact wait time for each game, so we will start sending requests until the server accepts them. This API is different from Hamster. The maximum delay time is calculated as (delay [~120 sec]) + (8 * (retry_delay [~20 sec] + a random delay between 1-5 sec)). This results in a maximum waiting time of approximately 320 seconds (5.33 minutes). That's it. Check recent commits too. If you are looking for other projects to get code from, you can search on GitHub. Hopefully, you will find them.

**Comment by Metercedes** [comment]
> We don't know the exact wait time for each game, so we will start sending requests until the server accepts them. This API is different from Hamster. The maximum delay time is calculated as (delay [~120 sec]) + (8 * (retry_delay [~20 sec] + a random delay between 1-5 sec)). This results in a maximum waiting time of approximately 320 seconds (5.33 minutes). That's it. Check recent commits too. If you are looking for other projects to get code from, you can search on GitHub. Hopefully, you will find them.

Longest I wait was 8.5 minutes. And still no result. So you're telling me no ETA, it could be even longer than 5mins?

**Comment by masterking32** [comment]
> > We don't know the exact wait time for each game, so we will start sending requests until the server accepts them. This API is different from Hamster. The maximum delay time is calculated as (delay [~120 sec]) + (8 * (retry_delay [~20 sec] + a random delay between 1-5 sec)). This results in a maximum waiting time of approximately 320 seconds (5.33 minutes). That's it. Check recent commits too. If you are looking for other projects to get code from, you can search on GitHub. Hopefully, you will find them.
> 
> Longest I wait was 8.5 minutes. And still no result. So you're telling me no ETA, it could be even longer than 5mins?

Use the last version that 5m.

**Comment by Metercedes** [comment]
I get it, now I set `"max_promo_games_per_round":` to **20** and also do you know any trusted proxy addresses to assign one? (Europe)

**Pull request merged**
