### PR TITLE
Zoopolis clientVersion Issue

### PR DESCRIPTION
**Pull request by tboy1337**
Wrong clientVersion, see [L34](https://gist.github.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968#file-hamster-kombat-playground-games-promo-keys-generator-js-L34)

### CODE REVIEW

**Comment by Fy0urM** [comment]
What makes you think his version is correct? I checked the version after your first PR.
check screenshot
https://github.com/masterking32/MasterHamsterKombatBot/pull/294

**Comment by tboy1337** [comment]
> What makes you think his version is correct? I checked the version after your first PR. check screenshot #294

I assumed newer is better but your right, im not sure which is correct, i've asked delasy if its correct and posted the picture you added, maybe we will find out something new.

**Comment by Fy0urM** [comment]
> > What makes you think his version is correct? I checked the version after your first PR. check screenshot #294
> 
> I assumed newer is better but your right, im not sure which is correct, i've asked delasy if its correct and posted the picture you added, maybe we will find out something new.

Maybe there is a version difference from android version (which is unlikely, I have the emulator on version 9), or a version difference between android and ios.

**Comment by tboy1337** [comment]
> > > What makes you think his version is correct? I checked the version after your first PR. check screenshot #294
> > 
> > 
> > I assumed newer is better but your right, im not sure which is correct, i've asked delasy if its correct and posted the picture you added, maybe we will find out something new.
> 
> Maybe there is a version difference from android version (which is unlikely, I have the emulator on version 9), or a version difference between android and ios.

There must be some difference because your information is newer but is showing an older clientVersion and his information is older and is showing a newer clientVersion.

**Comment by Fy0urM** [comment]
> > > > What makes you think his version is correct? I checked the version after your first PR. check screenshot #294
> > > 
> > > 
> > > I assumed newer is better but your right, im not sure which is correct, i've asked delasy if its correct and posted the picture you added, maybe we will find out something new.
> > 
> > 
> > Maybe there is a version difference from android version (which is unlikely, I have the emulator on version 9), or a version difference between android and ios.
> 
> There must be some difference because your both getting different clientVersions.

Maybe he just made a mistake, 7 and 8 are next to each other) or maybe he used a string from another game, I think there was already version 1.2.8 somewhere.

**Pull request closed without merging**
