### PR TITLE
MasterHamsterKombatBot Updater

### PR DESCRIPTION
**Pull request by tboy1337**
The updater is designed to continuously monitor and update all code and README files from the ```masterking32/MasterHamsterKombatBot/main``` repository with no changes to main.py like https://github.com/masterking32/MasterHamsterKombatBot/pull/190 and ensuring that the main.py, promogames.py etc. files are always running the most up-to-date version.  The script will probably only work on Windows and needs to be in the same folder as main.py, promogames.py, etc.  Here’s a summary of what the script does.

Key Features:

-     Continuous Monitoring

        The script runs in an infinite loop, checking for updates to the specified files at regular intervals (every 60 seconds by default).

-     File Comparison and Update

        It compares the local versions of the specified files (main.py, promogames.py, etc.) with their counterparts on GitHub.
        If differences are detected, the script downloads and updates the local files.

-     Process Management

        The script identifies and terminates the running process of main.py, regardless of whether it was started with py.exe or python.exe.  It ensures that the process is fully terminated before attempting to restart main.py in a new command window.

-     Graceful and Forceful Termination

        The script first attempts to gracefully terminate the main.py process.
        If the process does not terminate within a set time, it forcefully kills it.
        It includes retries and checks to confirm that the process is fully terminated.

-     Reopening the Main Script

        After updating the necessary files and confirming the old process is terminated, the script reopens main.py in a new command window using the python interpreter.

-     Error Handling and Logging

        The script includes error handling for various scenarios, such as failed downloads or process termination issues.
        It logs the steps it takes in the terminal window, including any errors encountered, making it easier to diagnose issues.

The branch for this PR is tboy1337:updater, this has the code addition of updater.py and the changes to README.MD.
Please check [Files changed](https://github.com/masterking32/MasterHamsterKombatBot/pull/246/files) for confirmation.

### CODE REVIEW

**Comment by Fy0urM** [comment]
Have you considered a variant of events when a new file is added that is necessary for the main script to work?  The updater will update the files it has links to, but the new file, which is necessary for work is not in the list for checking, will not be downloaded and the main script will crash.

**Comment by Fy0urM** [comment]
Even if a change made to the repository adds a link to the new file to the updater, your updater does not update itself to get links to the newly added files

**Comment by tboy1337** [comment]
@Fy0urM good point.

**Comment by tboy1337** [comment]
@Fy0urM I have a self updating version that updates itself successfully but then doesnt restart itself [updater.py](https://github.com/tboy1337/MasterHamsterKombatBot/blob/test/updater.py), take a look if you want.

**Comment by tboy1337** [comment]
Self updating version addressing the issues @Fy0urM mentioned ([Comment 1](https://github.com/masterking32/MasterHamsterKombatBot/pull/246#issuecomment-2314443947) [Comment 2](https://github.com/masterking32/MasterHamsterKombatBot/pull/246#issuecomment-2314451959)) available at [updater.py](https://github.com/tboy1337/MasterHamsterKombatBot/blob/test/updater.py), I've tested it and it seems like its working but its not as thoroughly tested as the one in the pull request so if someone wants to test it out that would be great.

**Pull request closed without merging**
