### PR TITLE
Logging updates

### PR DESCRIPTION
**Pull request by tboy1337**
Logging code now works, I checked and the bot was producing around 1.6MB of log files per day so now at the beginning of each week (Monday) the bot will zip the old log file and create a new one to save space.  Additionally the output.log file location has been changed to Logs/output.log as eventually there will be several files and also the zipped logs get their name changed so there isnt conflict with new zipped logs, tested working.

### CODE REVIEW

**Comment by tboy1337** [comment]
I forgot to add that therefore the log files will be reduced in size by approximately 90%.

**Comment by masterking32** [comment]
Please create a new PR by adding your changes on a branch. for each PR you need to create a new branch.

**Comment by tboy1337** [comment]
@masterking32 thats what I have done, the branch for this is tboy1337:logging, this only has the logging changes for main.py.

**Comment by tboy1337** [comment]
@masterking32 look in [Files changed](https://github.com/masterking32/MasterHamsterKombatBot/pull/238/files)

**Pull request closed without merging**
