### PR TITLE
Added playground game Pin Out Master

### PR DESCRIPTION
**Pull request by Fy0urM**
[Pin Out Master Tap Away Game.json](https://github.com/user-attachments/files/17040851/Pin.Out.Master.Tap.Away.Game.json)
[Count Masters.json](https://github.com/user-attachments/files/17042452/Count.Masters.json)
upd: ready to merge

### CODE REVIEW

**Review by Ashwin3454 — APPROVED** [review]

**Comment by tboy1337** [comment]
@Fy0urM why has `"auto_claim_daily_combo": True,` been removed?

**Comment by Fy0urM** [comment]
Because it unused, daily combo using 'auto_daily_combo_enabled'

**Comment by Ashwin3454** [comment]
@Fy0urM new game also added `Count Masters`

**Comment by Fy0urM** [comment]
> @Fy0urM new game also can be added `'Count Masters'`

i know, i edit PR firm comment

**Comment by tboy1337** [comment]
> Because it unused, daily combo using 'auto_daily_combo_enabled'

Ahh I see, im so tired of editing 16 config files to remove one line, I wish the account_name, Authorization, UserAgent and Proxy were in a seperate file than the rest of the config

**Comment by Fy0urM** [comment]
> > Because it unused, daily combo using 'auto_daily_combo_enabled'
> 
> Ahh I see, im so tired of editing 16 config files to remove one line, I wish the account_name, Authorization, UserAgent and Proxy were in a seperate file than the rest of the config

this is config example, this setting has not been used since the beginning of adding the daily combo, there is nothing wrong with just having it in your main config.

**Comment by tboy1337** [comment]
> > > Because it unused, daily combo using 'auto_daily_combo_enabled'
> > 
> > 
> > Ahh I see, im so tired of editing 16 config files to remove one line, I wish the account_name, Authorization, UserAgent and Proxy were in a seperate file than the rest of the config
> 
> this is config example, this setting has not been used since the beginning of adding the daily combo, there is nothing wrong with just having it in your main config.

Then eventually i would have a load of unused settings in my configs and no idea which ones are working or not lol, id rather stay as close to the example as i can tbh.

**Comment by tboy1337** [comment]
Ive made an issue about the subject (https://github.com/masterking32/MasterHamsterKombatBot/issues/467) if anyone wants to voice their approval/disapproval xD

**Comment by Fy0urM** [comment]
added

**Pull request merged**
