### PR TITLE
Added new promo games

### PR DESCRIPTION
**Pull request by Fy0urM**
@masterking32 
I'm not sure I've added the logic correctly, I'm attaching the files with the collected data for verification.
and for some reason `Tail Trio` disappeared from api get-promos while I was collecting and checking it.
[FluffClusade.txt](https://github.com/user-attachments/files/16870780/FluffClusade.txt)
[TileTrio.txt](https://github.com/user-attachments/files/16870783/TileTrio.txt)

### CODE REVIEW

**Comment by Ashwin3454** [comment]
[WARNING] 2024-09-04 18:33:04 Event registration for Fluff Crusade failed, retry in 185 seconds.

it happened in my all accounts

**Comment by Fy0urM** [comment]
> [WARNING] 2024-09-04 18:33:04 Event registration for Fluff Crusade failed, retry in 185 seconds.
> 
> it happened in my all accounts
> 
> `Tail Trio` was dissapeared in the game

Oops, that's my test message from my own modification. Wait for the full cycle to complete. I have everything working for the moment.

**Comment by Ashwin3454** [comment]
> > [WARNING] 2024-09-04 18:33:04 Event registration for Fluff Crusade failed, retry in 185 seconds.
> > it happened in my all accounts
> > `Tail Trio` was dissapeared in the game
> 
> Oops, that's my test message from my own modification. Wait for the full cycle to complete. I have everything working for the moment. 

same issue everytime.
Screenshot 2024-09-04 184938

**Comment by Fy0urM** [comment]
Well, then we need more data.
How did you update the script?

**Comment by Ashwin3454** [comment]
> Well, then we need more data. How did you update the script?

copied raw data from your updated file, then pasted in `main.py` & `promogames.py`

**Comment by Fy0urM** [comment]
from PR or from my branch https://github.com/Fy0urM/MasterHamsterKombatBot/tree/upd/playgroundgames ?
make sure you do it right.

**Comment by Fy0urM** [comment]
working fine on my 2 accounts on 2 pcs on linux and win10
image
but this is my mod, i need to check my fork

**Comment by Ashwin3454** [comment]
> from PR or from my branch https://github.com/Fy0urM/MasterHamsterKombatBot/tree/upd/playgroundgames ? make sure you do it right.

From PR

**Comment by Fy0urM** [comment]
researching

**Comment by Fy0urM** [comment]
yes, that was my mistake. fixed it. replace “newApi” to “useNewApi” in promogames.py for Fluff Crusade or grab the update from PR or the branch

**Comment by Ashwin3454** [comment]
> yes, that was my mistake. fixed it. replace “newApi” to “useNewApi” in promogames.py for Fluff Crusade or grab the update from PR or the branch

its okay, thank you so much

**Comment by Fy0urM** [comment]
Anybody got any info on why Tail Trio got deleted? I'm so fucked up waiting for requests in this crap.

**Comment by Fy0urM** [comment]
> > yes, that was my mistake. fixed it. replace “newApi” to “useNewApi” in promogames.py for Fluff Crusade or grab the update from PR or the branch
> 
> its okay, thank you so much

Tell me if the patched version works or not

**Comment by Go0p** [comment]
> > > yes, that was my mistake. fixed it. replace “newApi” to “useNewApi” in promogames.py for Fluff Crusade or grab the update from PR or the branch
> > 
> > 
> > its okay, thank you so much
> 
> Tell me if the patched version works or not

It works fine.

image

**Comment by Fy0urM** [comment]
> It works fine.

thank you very much

**Comment by Lastnet0709** [comment]
image

working

**Comment by Ashwin3454** [comment]
> > > yes, that was my mistake. fixed it. replace “newApi” to “useNewApi” in promogames.py for Fluff Crusade or grab the update from PR or the branch
> > 
> > 
> > its okay, thank you so much
> 
> Tell me if the patched version works or not

Yes its working now. is it possible to know how many coins recieved after one code redeemed?

**Comment by Fy0urM** [comment]
> Yes its working now. is it possible to know how many coins recieved after one code redeemed?

maybe I'll check it out.

**Comment by miladesign** [comment]
@Fy0urM why you removed `headers_post["Authorization"] = f"Bearer {clientToken}"` for register-event if it useNewApi is false its not sending it? for old promo games

**Comment by vanhbakaa** [comment]
old promogame is not working anymore

**Comment by Fy0urM** [comment]
> @Fy0urM why you removed `headers_post["Authorization"] = f"Bearer {clientToken}"` for register-event if it useNewApi is false its not sending it? for old promo games

Thanks for finding the mistake, I fixed it.

**Comment by miladesign** [comment]
fix this too :D `rewarmAmount = claimResponse.get("reward").get("amount")` (rewarm?)

**Comment by vanhbakaa** [comment]
and also key is not counting 

> old promogame is not working anymore

**Comment by Fy0urM** [comment]
> fix this too :D `rewarmAmount = claimResponse.get("reward").get("amount")` (rewarm?)

thx

**Comment by vanhbakaa** [comment]
it claimed key for new game but Total keys doesnt count . Check that

**Comment by Fy0urM** [comment]
> it claimed key for new game but Total keys doesnt count . Check that

the new Fluff Crusade game doesn't give you keys, it gives you coins.

**Comment by epis78** [comment]
fluff

**Comment by Fy0urM** [comment]
> fluff

thx

**Comment by Lastnet0709** [comment]
> someone please show me how the received reward for using the key is displayed.

like this ? 
image

**Comment by vanhbakaa** [comment]
Screenshot_20240904-221257

**Comment by Fy0urM** [comment]
> Screenshot_20240904-221257

Does anyone else have the same error?

**Comment by Lastnet0709** [comment]
image
with the same script, one of 3 accounts

**Comment by Fy0urM** [comment]
hmm, I don't have this error neither in fork nor in personal mod on different accounts. did you not enter the key yourself in the game while the bot was trying to get the key?

**Comment by Fy0urM** [comment]
Deleted the test account twice and ran a full cycle on all keys for Fluff, did not encounter the problem.

**Comment by Fy0urM** [comment]
It's funny, even though Tile Trio is removed from the app now, you can still get keys for it and activate them and you get a key in hamster. not sure if it's safe)

**Comment by MeninSun** [comment]
> from PR or from my branch https://github.com/Fy0urM/MasterHamsterKombatBot/tree/upd/playgroundgames ? make sure you do it right.

work fine for fluff
image

but this happen for other playground :
image

**Comment by Fy0urM** [comment]
also interestingly, updates with hamsters were added to the tile trio on August 30.
image

**Comment by MeninSun** [comment]
> > but this happen for other playground
> 
> These are additional lines from my modification, I forgot to remove them. I think they do not interfere much, were added for informativeness that the bot did not hang while getting keys.

**update** : it will still get key by retrying again and again.

this is you forgot to add or not? i try to add this :
image

**Comment by Fy0urM** [comment]
> > > but this happen for other playground
> > 
> > 
> > These are additional lines from my modification, I forgot to remove them. I think they do not interfere much, were added for informativeness that the bot did not hang while getting keys.
> 
> **update** : it will still get key by retrying again and again.
> 
> this is you forgot to add or not? i try to add this : image

I'm not sure what you mean.

**Comment by Fy0urM** [comment]
ah I get it, no, it's fine there. older games don't use the get-client request, only Fluff Crusade and Tile Trio at the moment.
About the message, yes, it appears every time a key is not issued, the bot did the same thing before, it just didn't have that message. for some games to get a key you need to send register-event request several times.

**Comment by MeninSun** [comment]
> ah I get it, no, it's fine there. older games don't use the get-client request, only Fluff Crusade and Tile Trio at the moment. About the message, yes, it appears every time a key is not issued, the bot did the same thing before, it just didn't have that message. for some games to get a key you need to send register-event request several times.

Got it! Thank you,

**Comment by AmirhN1382** [comment]
Fluff crusade works fine for me Tile Trio looks to be removed from the bot for now. Merging.

**Pull request merged**
