### PR TITLE
Update userAgent for Merge Away in promogames.py

### PR DESCRIPTION
**Pull request by tboy1337**
Here is the [Source](https://gist.github.com/delasy/96c5340fc5e0617ddc1ff4ddb458d968?permalink_comment_id=5170447#gistcomment-5170447) of the information (Its on Line 121 now as the code has been updated).  It seems that Merge Away sends the device userAgent so instead of none ive added a Samsung Galaxy S23 which is different from what delasy has set for his.

### CODE REVIEW

**Review by Fy0urM — COMMENTED** [review]
I suspect that the useragent in this game is different for each device, on my emulator it has this value
`Mozilla/5.0 (Linux; Android 9; NE2211 Build/SKQ1.220617.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.105 Mobile Safari/537.36`

**Comment by masterking32** [comment]
Please fix your PRs, and create a new fork with just one commit, None for user-agent = Account User-agent.

**Comment by tboy1337** [comment]
@masterking32 I really dont think you have paid attention to what i have posted.....  The game sends a user agent, the bot doesnt send a user agent, therfor issue, issue needs to be fixed, not just close PR and tell me that i need to put the change in a new fork.  Ive created a new branch for it, why do you keep asking this.......

**Comment by Fy0urM** [comment]
> I really dont think you have paid attention to what i have posted..... The game sends a user agent, the bot doesnt send a user agent, therefore issue, issue needs to be fixed, not just close PR and tell me that I need to put the change in a new fork. Ive created a new branch for it, why do you keep asking this, first its a new branch, now a new fork, all you need to do is look at files changed.......



> None for user-agent = Account User-agent.

It has been explained to you, if the game does not have a userAgent, the userAgent from config.py set for the account is used, this is correct because the game userAgent = device userAgent.

**Comment by Fy0urM** [comment]
> None for user-agent = Account User-agent.

Here's the explanation

**Pull request closed without merging**
