### PR TITLE
Added both windows and linux/mac setup commands to the readme

### PR DESCRIPTION
**Pull request by tboy1337**
Added both windows and linux/mac setup commands to the readme.

### CODE REVIEW

**Comment by Fy0urM** [comment]
hey, don't do sync for branches other than main, especially if there is an active PR for the branch, sync only the main branch and after sync the main branch create a new branch to make changes for the PR

**Comment by tboy1337** [comment]
so cancel the pr and make a new one you mean? sorry but im not so good with git lol

**Comment by Fy0urM** [comment]
> so cancel the pr and make a new one you mean? sorry but im not so good with git lol

not for this, but for the future

**Comment by tboy1337** [comment]
I see, ok thanks for the information

**Pull request closed without merging**
