### PR TITLE
simple updater

### PR DESCRIPTION
**Pull request by qawechi**

### CODE REVIEW

**Comment by Fy0urM** [comment]
what happens if a user doesn't have git and downloaded the bot as a zip?

**Comment by Fy0urM** [comment]
also the command will work only if MaxRandomDelay > 0, for example, I have MaxRandomDelay = 0.

**Comment by qawechi** [comment]
```
import os
import git
import subprocess

def update_if_git_repo(repo_path):
    if os.path.isdir(repo_path):
        git_dir = os.path.join(repo_path, '.git')
        if os.path.isdir(git_dir):
            try:
                repo = git.Repo(repo_path)
                # Execute git pull
                subprocess.run(["git", "pull", "origin", "main"], cwd=repo_path)
            except git.exc.InvalidGitRepositoryError:
                pass

# Example usage
repo_path = '/path/to/the/repo'
update_if_git_repo(repo_path)
```

and of course we need:
`pip install gitpython`

**Comment by qawechi** [comment]
```
import os
import git
import subprocess
import sys

def update_if_git_repo(repo_path):
    if os.path.isdir(repo_path):
        git_dir = os.path.join(repo_path, '.git')
        if os.path.isdir(git_dir):
            try:
                repo = git.Repo(repo_path)
                # Execute git pull
                subprocess.run(["git", "pull", "origin", "main"], cwd=repo_path)
                # Restart the script
                print("Restarting script...")
                os.execv(sys.executable, ['python'] + sys.argv)
            except git.exc.InvalidGitRepositoryError:
                pass

# Example usage
repo_path = '/path/to/the/repo'
update_if_git_repo(repo_path)

```

I am sorry i have zero knowledge about github haha should I make another request every time i make a change? or how can I edit the request?

**Comment by Fy0urM** [comment]
If you are not doing it on the github itself, but locally on a pc, just commit to the same branch of your local fork as the previous change and submit it to your branch on the github, the new change will automatically be added to the existing PR

**Comment by Fy0urM** [comment]
Have you checked this code? I'm not sure, but I think it has errors.

- `if os.path.isdir(repo_path):` - check if the path exists on the device? If I'm not mistaken, you can't create a path `https://github.com/masterking32/MasterHamsterKombatBot.git` on either windows or linux.
- `git_dir = os.path.join(repo_path, '.git')` - add 1 more `.git' to the url `https://github.com/masterking32/MasterHamsterKombatBot.git` to make `https://github.com/masterking32/MasterHamsterKombatBot.git.git`?
- `os.execv(sys.executable, ['python'] + sys.argv)` - even if the updated main.py runs, what happens to the one that ran it? will it close?
- `repo_path = 'https://github.com/masterking32/MasterHamsterKombatBot.git'
update_if_git_repo(repo_path)` - will it work once at startup?

**Comment by tboy1337** [comment]
check this updater out, doesnt require the user to have installed with GIT:
[updater.py](https://github.com/tboy1337/MasterHamsterKombatBot/blob/updater/updater.py)

**Comment by AmirhN1382** [comment]
Thanks for PR, but we dont need an updater. Soon, we will move to the new platform https://github.com/masterking32/MasterCryptoFarmBot, so the auto update feature wouldn't be an issue.
There will also be more bots there, not only hamster kombat. Stay tuned for more.

**Pull request closed without merging**
