### PR TITLE
Automatically check for any updates to main.py and apply the update if there is

### PR DESCRIPTION
**Pull request by yusefgharib**
Instead of checking everyday if there is an update and manually overwriting the code, this will allow for automatic updates

### CODE REVIEW

**Comment by ashwin8454** [comment]
can u make for other files too? excluding the config file.

**Comment by masterking32** [comment]
https://github.com/masterking32/MasterHamsterKombatBot?tab=readme-ov-file#-update-to-the-latest-version

**Comment by vashamamasha2014** [comment]
please check my updates for "utilities.py" and "promogames.py"
```
import os
import sys
import requests
import time

# Constants
LOCAL_FILE_MAIN = "main.py"
GITHUB_RAW_URL_MAIN = "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/main.py"
LOCAL_FILE_PROMO = "promogames.py"
GITHUB_RAW_URL_PROMO = "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/promogames.py"
LOCAL_FILE_UTIL = "utilities.py"
GITHUB_RAW_URL_UTIL = "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/utilities.py"
RESTART_DELAY = 2  # Delay in seconds before restarting

def get_local_file_contents(file_path):
    with open(file_path, 'r') as file:
        contents = file.readlines()
    # Exclude the update logic section
    start_marker = "# BEGIN_UPDATE_LOGIC"
    end_marker = "# END_UPDATE_LOGIC"
    in_update_section = False
    filtered_contents = []
    for line in contents:
        if start_marker in line:
            in_update_section = True
        if not in_update_section:
            filtered_contents.append(line)
        if end_marker in line:
            in_update_section = False
    return "".join(filtered_contents)

def get_github_file_contents(url):
    response = requests.get(url)
    if response.status_code == 200:
        return response.text
    else:
        response.raise_for_status()

def check_for_updates():
    try:
        updates_needed = []
        
        # Check main.py
        local_contents_main = get_local_file_contents(LOCAL_FILE_MAIN)
        github_contents_main = get_github_file_contents(GITHUB_RAW_URL_MAIN)
        if local_contents_main != github_contents_main:
            updates_needed.append(LOCAL_FILE_MAIN)
        
        # Check promogames.py
        local_contents_promo = get_local_file_contents(LOCAL_FILE_PROMO)
        github_contents_promo = get_github_file_contents(GITHUB_RAW_URL_PROMO)
        if local_contents_promo != github_contents_promo:
            updates_needed.append(LOCAL_FILE_PROMO)

        # Check utilities.py
        local_contents_util = get_local_file_contents(LOCAL_FILE_UTIL)
        github_contents_util = get_github_file_contents(GITHUB_RAW_URL_UTIL)
        if local_contents_util != github_contents_util:
            updates_needed.append(LOCAL_FILE_UTIL)
        
        return updates_needed
    except Exception as e:
        print(f"Error checking for updates: {e}")
        return []

def download_update(file_name, url):
    try:
        github_contents = get_github_file_contents(url)
        with open(file_name, 'w') as file:
            file.write(github_contents)
        return True
    except Exception as e:
        print(f"Error downloading update for {file_name}: {e}")
        return False

def restart_program():
    try:
        print("Restarting program...")
        time.sleep(RESTART_DELAY)  # Optional delay before restarting
        python = sys.executable
        os.execl(python, python, *sys.argv)
    except Exception as e:
        print(f"Error restarting program: {e}")

def update_check():
    updates_needed = check_for_updates()
    if updates_needed:
        print("New versions available for the following files:", updates_needed)
        all_updates_successful = True
        for file_name in updates_needed:
            url = {
                LOCAL_FILE_MAIN: GITHUB_RAW_URL_MAIN,
                LOCAL_FILE_PROMO: GITHUB_RAW_URL_PROMO,
                LOCAL_FILE_UTIL: GITHUB_RAW_URL_UTIL
            }[file_name]
            if not download_update(file_name, url):
                all_updates_successful = False
                print(f"Failed to download update for {file_name}.")
        if all_updates_successful:
            print("All updates downloaded successfully. Restarting program...")
            restart_program()
        else:
            print("Some updates failed. Please check the logs.")
    else:
        print("No updates available.")

# Run the update check
update_check()
```

**Comment by masterking32** [comment]
> > https://github.com/masterking32/MasterHamsterKombatBot?tab=readme-ov-file#-update-to-the-latest-version
> 
> if you havnt installed via git cli you are kind of stuck for automatic updates then though.

It's not hard to switch to Git.
Just create a copy of your config file, install Git, clone the project with `git clone https://github.com/masterking32/MasterHamsterKombatBot`, 
then copy your config file into the MasterHamsterKombatBot folder and run the project.

**Comment by tboy1337** [comment]
> > > https://github.com/masterking32/MasterHamsterKombatBot?tab=readme-ov-file#-update-to-the-latest-version
> > 
> > 
> > if you havnt installed via git cli you are kind of stuck for automatic updates then though.
> 
> It's not hard to switch to Git. Just create a copy of your config file, install Git, and clone the project with `git clone https://github.com/masterking32/MasterHamsterKombatBot` then copy your config file into the MasterHamsterKombatBot folder and run the project.
> 
> for update just run `git pull origin main`

I have 5+ copyies of the program running at the same time from seperate folders so I dont think that would work for me.

**Comment by tboy1337** [comment]
This needs to check [https://github.com/masterking32/MasterHamsterKombatBot/blob/main/config.py.example](url) too and should also check the [https://github.com/masterking32/MasterHamsterKombatBot/tree/main/useful_files](url) folder.

**Comment by tboy1337** [comment]
```
import os
import sys
import requests
import time

# Constants
FILES = {
    "useful_files/hamsterkombat.io-telegram-web-app.php": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/useful_files/hamsterkombat.io-telegram-web-app.php",
    "useful_files/hamsterkombat.js": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/useful_files/hamsterkombat.js",
    "useful_files/user-agents.md": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/useful_files/user-agents.md",
    ".gitignore": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/.gitignore",
    "README.MD": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/README.MD",
    "config.py.example": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/config.py.example",
    "main.py": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/main.py",
    "promogames.py": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/promogames.py",
    "requirements.txt": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/requirements.txt",
    "utilities.py": "https://raw.githubusercontent.com/masterking32/MasterHamsterKombatBot/main/utilities.py"
}
CHECK_DELAY = 5  # Delay in seconds between each update check cycle

def get_local_file_contents(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            contents = file.read()
        return contents
    except UnicodeDecodeError as e:
        print(f"Error reading local file {file_path}: {e}")
        return None
    except Exception as e:
        print(f"General error reading local file {file_path}: {e}")
        return None

def get_github_file_contents(url):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            return response.text
        else:
            print(f"Error fetching file from GitHub: {url} - Status Code: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching file from GitHub: {e}")
        return None

def check_for_updates():
    updates_needed = []
    for local_file, github_url in FILES.items():
        local_contents = get_local_file_contents(local_file)
        github_contents = get_github_file_contents(github_url)
        if local_contents is None or github_contents is None:
            continue  # Skip this file if there's an error
        if local_contents != github_contents:
            updates_needed.append(local_file)
            print(f"Update needed for {local_file}")
        else:
            print(f"No update needed for {local_file}")
    return updates_needed

def download_update(file_name, github_url):
    github_contents = get_github_file_contents(github_url)
    if github_contents is None:
        return False
    try:
        with open(file_name, 'w', encoding='utf-8') as file:
            file.write(github_contents)
        print(f"Successfully updated {file_name}")
        return True
    except UnicodeEncodeError as e:
        print(f"Error writing to file {file_name}: {e}")
        return False
    except Exception as e:
        print(f"General error writing to file {file_name}: {e}")
        return False

def update_check():
    updates_needed = check_for_updates()
    if updates_needed:
        all_updates_successful = True
        for file_name in updates_needed:
            github_url = FILES[file_name]
            if not download_update(file_name, github_url):
                all_updates_successful = False
        if all_updates_successful:
            print("All updates downloaded.")
        else:
            print("Some updates failed to download.")
    else:
        print("No updates available.")

# Main loop to continuously check for updates
def main_loop():
    while True:
        update_check()
        print(f"Waiting {CHECK_DELAY} seconds before next check...")
        time.sleep(CHECK_DELAY)  # Wait before checking again

# Start the main loop
if __name__ == "__main__":
    main_loop()
```

Here's a better version that runs on a timed loop and updates all useful files.

**Comment by masterking32** [comment]
> > > > https://github.com/masterking32/MasterHamsterKombatBot?tab=readme-ov-file#-update-to-the-latest-version
> > > 
> > > 
> > > if you havnt installed via git cli you are kind of stuck for automatic updates then though.
> > 
> > 
> > It's not hard to switch to Git. Just create a copy of your config file, install Git, and clone the project with `git clone https://github.com/masterking32/MasterHamsterKombatBot` then copy your config file into the MasterHamsterKombatBot folder and run the project.
> > for update just run `git pull origin main`
> 
> I have 5+ copies of the program running at the same time from separate folders so I dont think that would work for me.

Create a bash/bat file for that.

```
cd MasterHamsterKombatBot1
git pull origin main
cd ../MasterHamsterKombatBot2
git pull origin main
cd ../MasterHamsterKombatBot3
git pull origin main
```

**Pull request closed without merging**
