### PR TITLE
Added Polysphere: Art Puzzle Game

### PR DESCRIPTION
**Pull request by Fy0urM**

### CODE REVIEW

**Comment by notghanati** [comment]
fast and furious :)

**Comment by Metercedes** [comment]
I didn't understand, there are no updates on the repository but in here stuff has changed what?

**Comment by Fy0urM** [comment]
> I didn't understand, there are no updates on the repository but in here stuff has changed what?

I don't quite understand you. I'm not a native English speaker. which repository doesn't have updates? has it changed where?

**Comment by Fy0urM** [comment]
> > > I didn't understand, there are no updates on the repository but in here stuff has changed what?
> > 
> > 
> > I don't quite understand you. I'm not a native English speaker. which repository doesn't have updates? has it changed where? if you about [register-event endloop](https://github.com/masterking32/MasterHamsterKombatBot/pull/205/commits/1dfbe00653239debe5a664312eaf4675c5e35275), in you script its says "Event registered successfully" if retrys is gone and hasCode in response is False
> 
> I am not entirely sure how different I can explain this to you. What is your native language?

russian))

**Comment by eeak** [comment]
> I didn't understand, there are no updates on the repository but in here stuff has changed what?
You can see the changes if you go to the tab "Commits". Once the owner accepts the commit, you will see the changes in the repository.

**Comment by Fy0urM** [comment]
> I didn't understand, there are no updates on the repository but in here stuff has changed what?

I think I get it, I'm an idiot, I didn't pay attention to your nickname and mistook you for the repository author. I guess your question is that something is changed here, but there are no changes to the repository itself? This is a pull request, the repository owner has to approve these changes to be made to the repository itself.

**Comment by Metercedes** [comment]
> > I didn't understand, there are no updates on the repository but in here stuff has changed what?
> 
> I think I get it, I'm an idiot, I didn't pay attention to your nickname and mistook you for the repository author. I guess your question is that something is changed here, but there are no changes to the repository itself? This is a pull request, the repository owner has to approve these changes to be made to the repository itself.
> 
> If you want to use the changes I made right now, you can download them from my repository.

yep I meant that. bc I cant see the updated repository.

**Review by masterking32 — APPROVED** [review]

**Pull request merged**
