### PR TITLE
💎 Session 2 main.py

### PR DESCRIPTION
**Pull request by CallMyNameStar**
semi update of session 2

### CODE REVIEW

**Comment by virginpixel** [comment]
Is this file not completing the playground games?

**Comment by yogizigova** [comment]
> semi update of session 2
error like this bro
.../airdrop/hamster $ python [main.py](https://main.py/)
  File "/storage/emulated/0/airdrop/hamster/[main.py](https://main.py/)", line 1768
    f"{[w.rs](https://w.rs/)}{w.g}[{self.account_name}]{[w.rs](https://w.rs/)}: 💰 Account Balance Coins: {w.y}{number_to_string(float("{:.2f}".format(float("{:.2f}".format(self.balanceCoins)))))}"
                                                                                                        ^
SyntaxError: invalid decimal literal

**Comment by Microzibert** [comment]
```
   f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float("{:.2f}".format(self.balanceCoins)))}"
                                                                                                        ^
SyntaxError: invalid decimal literal
```

**Comment by Fy0urM** [comment]
why this removed?
`elif promoData["clientIdType"] == "ts+19dig":`
Count masters not in game?

**Comment by yogizigova** [comment]
> > > semi update of session 2
> > > error like this bro
> > > .../airdrop/hamster $ python [main.py](https://main.py/)
> > > File "/storage/emulated/0/airdrop/hamster/[main.py](https://main.py/)", line 1768
> > > f"{[w.rs](https://w.rs/)}{w.g}[{self.account_name}]{[w.rs](https://w.rs/)}: 💰 Account Balance Coins: {w.y}{number_to_string(float("{:.2f}".format(float("{:.2f}".format(self.balanceCoins)))))}"
> > > ^
> > > SyntaxError: invalid decimal literal
> 
> fixed✅

photo_6301083616326828028_y
same error

**Comment by yogizigova** [comment]
> why this removed? `elif promoData["clientIdType"] == "ts+19dig":` Count masters not in game?

please fix bro

**Comment by Fy0urM** [comment]
> ```
>    f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float("{:.2f}".format(self.balanceCoins)))}"
>                                                                                                         ^
> SyntaxError: invalid decimal literal
> ``` 

You need to fix all f-strings that have " inside them and replace it with '
Like this 

```python
f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float('{:.2f}'.format(self.balanceCoins)))}"
```

**Comment by yogizigova** [comment]
> > ```
> >    f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float("{:.2f}".format(self.balanceCoins)))}"
> >                                                                                                         ^
> > SyntaxError: invalid decimal literal
> > ```
> 
> You need to fix all f-strings that have " inside them and replace it with ' Like this
> 
> ```python
> f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float('{:.2f}'.format(self.balanceCoins)))}"
> ```

I have tried to fix this program, by changing f"{w.rs}{w.g}[{self.account_name}]{w.rs}: 💰 Account Balance Coins: {w.y}{number_to_string(float(self.balanceCoins)):.2f}", like this but this program still errors because the str format has not been changed to float, I'm stuck because I don't know where the str format is to be changed.

**Comment by Fy0urM** [comment]
I've just sat down at my pc, I'll look into the problem on linux and tell you how to solve it.

**Comment by Fy0urM** [comment]
I was right, just the problem is not in 1 line but in many, you need to open main.py in a normal editor that has a find and resplace function, in the find field write `“{:.2f}”` and in the replace field write `'{:.2f}'` and click replace all.

**Comment by Microzibert** [comment]
The bot does not buy a free card in the store

**Comment by Fy0urM** [comment]
> The bot does not buy a free card in the store

Questions to the PR author, I have not yet studied the changes in the game after the close of the season and can not tell you anything

**Comment by yogizigova** [comment]
> I was right, just the problem is not in 1 line but in many, you need to open main.py in a normal editor that has a find and resplace function, in the find field write
> 
> ```python
> "{:.2f}"
> ```
> 
> and in the replace field write
> 
> ```python
> '{:.2f}'
> ```
> 
> and click replace all.

this works bro, but i hope this program can complete the key generator on Playground Game

photo_6301083616326828077_y (1)

**Comment by Fy0urM** [comment]
I think that in order for card buying to work you need to reduce these values in config.py
“auto_upgrade_start":
“auto_upgrade_min":
because the currency has changed and its amount has changed too, and the script checks your balance with the set values and if the balance is lower than “auto_upgrade_start” the bot does not start buying cards and if the balance is lower than “auto_upgrade_min” and buying cards is in process the bot completes the buying cycle

**Comment by yogizigova** [comment]
> I think that in order for card buying to work you need to reduce these values in config.py
> “auto_upgrade_start":
> “auto_upgrade_min":
> because the currency has changed and its amount has changed too, and the script checks your balance with the set values and if the balance is lower than “auto_upgrade_start” the bot does not start buying cards and if the balance is lower than “auto_upgrade_min” and buying cards is in process the bot completes the buying cycle

what is the lowest value I should set?

**Comment by Fy0urM** [comment]
> > I think that in order for card buying to work you need to reduce these values in config.py
> > “auto_upgrade_start":
> > “auto_upgrade_min":
> > because the currency has changed and its amount has changed too, and the script checks your balance with the set values and if the balance is lower than “auto_upgrade_start” the bot does not start buying cards and if the balance is lower than “auto_upgrade_min” and buying cards is in process the bot completes the buying cycle
> 
> what is the lowest value I should set?

i thinI don't know yet, set the value based on this information.
“auto_upgrade_start” - if the balance is above this value, the bot will buy improvements, if below, it will not
 “auto_upgrade_min” - if the balance is lower than this value, the bot will skip the cycle of buying improvements, but everything should be checked.

**Comment by Fy0urM** [comment]
i set both to 0 and it works
image

**Comment by yogizigova** [comment]
> i set both to 0 and it works

playground game why can't the program run bro?

**Comment by Microzibert** [comment]
The bot buys all cards except the free one. 
```
"auto_upgrade": True,
"wait_for_best_card": True,
"enable_parallel_upgrades": True,
```

**Comment by Fy0urM** [comment]
> playground game why can't the program run bro?

because for some reason the author excluded the loop responsible for playground games from the main loop of the script.

**Comment by yogizigova** [comment]
> I think this is absolutely normal since "Free" is a string.
> And the bot is designed to buy only those cards with the value integer



> The bot buys all cards except the free one.
> 
> ```
> "auto_upgrade": True,
> "wait_for_best_card": True,
> "enable_parallel_upgrades": True,
> ```
> 
> I think this is absolutely normal since "Free" is a string. And the bot is designed to buy only those cards with the value integer

of course I can have it

**Comment by yogizigova** [comment]
> because for some reason the author excluded the loop responsible for playground games from the main loop of the script.
does that mean that part is deleted?

**Comment by Fy0urM** [comment]
> > does that mean that part is deleted?

No, it is not deleted, just the author of this PR for some reason excluded the function call from the main loop, I don't know why.

**Comment by yogizigova** [comment]
> > > does that mean that part is deleted?
> 
> No, it is not deleted, just the author of this PR for some reason excluded the function call from the main loop, I don't know why.

I've added it bro, but the task to invite friends is still buggy bro

**Comment by Fy0urM** [comment]
> I've added it bro, but the task to invite friends is still buggy bro

because the tasks ids have changed, I'm already working on a minimal update for interlude.

**Comment by yogizigova** [comment]
> because the tasks ids have changed, I'm already working on a minimal update for interlude.

Cheers bro, I'll wait for your update

**Comment by masterking32** [comment]
Please stop working on this project. If you are a developer, start focusing on our new project by creating a new module for [MasterCryptoFarmBot](https://github.com/masterking32/MasterCryptoFarmBot) using the [MCF Example Module](https://github.com/masterking32/MCF_ExampleModule) as a reference.

**Comment by tboy1337** [comment]
@masterking32 aren't you going to port this bot in as a module?

**Pull request closed without merging**
