### PR TITLE
Start With System Proxy.bat

### PR DESCRIPTION
**Pull request by CipherVasat**
As for VPN apps out there most of them set system proxy this bat file change proxy for CMD.exe to use system proxy ( needs to be configured in the bat file) then launch the main.py

### CODE REVIEW

**Comment by Fy0urM** [comment]
And what is it for? The proxy is configured in config.py for each account individually.

**Comment by CipherVasat** [comment]
> And what is it for? The proxy is configured in config.py for each account individually.

didn't know the poxy in config.py can also be used for system proxy which is in windows settings, thought have to use non local proxies

**Comment by tboy1337** [comment]
This approach doesn't work for multiple accounts, [netsh](https://learn.microsoft.com/en-us/troubleshoot/windows-server/installing-updates-features-roles/windows-update-client-determines-proxy-server-connect#the-netshexe-tool) sets the system-wide proxy but if you put the proxies in the config.py you can set it for each individual account.

**Comment by tboy1337** [comment]
> > And what is it for? The proxy is configured in config.py for each account individually.
> 
> didn't know the poxy in config.py can also be used for system proxy which is in windows settings, thought have to use non local proxies

This approach doesn't work for multiple accounts, [netsh](https://learn.microsoft.com/en-us/troubleshoot/windows-server/installing-updates-features-roles/windows-update-client-determines-proxy-server-connect#the-netshexe-tool) sets the system-wide proxy but if you put the proxies in the config.py you can set it for each individual account.  See https://github.com/masterking32/MasterHamsterKombatBot/discussions/133 for more information.

**Comment by masterking32** [comment]
This feature is not usable for everyone, so we cannot merge it. However, thank you for your PR.

**Pull request closed without merging**
